char SpotTheDifference(string s, string t){
	var letterPool = s.ToHashSet();
	return t.ToCharArray().FirstOrDefault(x => !letterPool.Contains(x));
}

// This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. 
// t is generated by shuffling the letters in s as well as potentially adding an additional random character. 
// Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘. 
// Note: You may assume that at most one additional character can be added to t. 
//
// Ex: Given the following strings...
// s = "foobar", t = "barfoot", return 't'
//Console.WriteLine(SpotTheDifference("foobar","barfoot"));
// s = "ide", t = "idea", return 'a'
//Console.WriteLine(SpotTheDifference("ide","idea"));
// s = "coding", t "ingcod", return ''
//Console.WriteLine(SpotTheDifference("coding","ingcod"));